### ISSUE TITLE
Whether `gem opal-rails` in Gemfile, will result in differnt behavior.

### ISSUE THREAD

**Issue by zw963** [ruby-hyperloop/hyper-react#217]
following is my project for test this issue.

In zw963/test_rails_5.1_project@2f86077 commit, we can start rails server successfully.

```sh
WARNING: Nokogiri was built against LibXML version 2.9.1, but has dynamically loaded 2.9.4
=> Booting Puma
=> Rails 5.1.2 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.9.1 (ruby 2.3.3-p222), codename: Private Caller
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop

```

But, that not true, seem like all client js.rb file is not start.

we have to add `opal-rails` gem into Gemfile, as in zw963/test_rails_5.1_project@f583946.

it seem like worked.

```sh
=> Booting Puma
=> Rails 5.1.2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options


##########################################################################
      HYPERLOOP LIBRARIES PRECOMPILING AND MINIFYING
  FIRST TIME BOOTING YOUR APP IT CAN TAKE 1 OR 2 MINUTES
 NB: You can force precompiling again by cleaning cache: rm -rf tmp/cache 
##########################################################################

Compiling the system assets for hyperloop-prerender-loader-system-code
    require 'opal' 
    require 'hyperloop-config' 
    require 'hyper-store' 
    require 'react/react-source-browser' 
    require 'react/react-source-server' # SERVER ONLY
    require 'hyper-react' 
  compiled -  length: 2665524
  total time: 2.4 seconds


##########################################################################
      HYPERLOOP LIBRARIES PRECOMPILING AND MINIFYING
  FIRST TIME BOOTING YOUR APP IT CAN TAKE 1 OR 2 MINUTES
 NB: You can force precompiling again by cleaning cache: rm -rf tmp/cache 
##########################################################################

Compiling the system assets for hyperloop-loader-system-code
    require 'opal' 
    require 'browser' # CLIENT ONLY
    require 'hyperloop-config' 
    require 'hyper-store' 
    require 'react/react-source-browser' 
    require 'opal-jquery' # CLIENT ONLY
    require 'browser/delay' # CLIENT ONLY
    require 'react_ujs' # CLIENT ONLY
    require 'hyper-react' 
Exiting
/home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/resolve.rb:65:in `resolve!': couldn't find file 'browser' with type 'application/javascript' (Sprockets::FileNotFound)
Checked in these paths: 
  /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/opal-0.10.5/opal
  /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/opal-0.10.5/stdlib
  /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/opal-0.10.5/lib
  /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/opal-jquery-0.4.2/lib
  /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/opal-activesupport-0.3.0/opal
  /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/hyperloop-config-0.9.10/lib
  /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/hyper-store-0.2.3/lib
  /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/hyper-react-0.12.7/lib
  /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/react-rails-1.11.0/lib/assets/react-source/development-with-addons
  /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/hyper-react-0.12.7/lib/react-sources
  /home/zw963/Project/opal/test_rails_5.1_project/app/assets/config
  /home/zw963/Project/opal/test_rails_5.1_project/app/assets/images
  /home/zw963/Project/opal/test_rails_5.1_project/app/assets/javascripts
  /home/zw963/Project/opal/test_rails_5.1_project/app/assets/stylesheets
  /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/jquery-rails-4.3.1/vendor/assets/javascripts
  /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/opal-rails-0.9.3/lib/assets/javascripts
  /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/coffee-rails-4.2.2/lib/assets/javascripts
  /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/actioncable-5.1.2/lib/assets/compiled
  /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/actionview-5.1.2/lib/assets/compiled
  /home/zw963/Project/opal/test_rails_5.1_project/app/hyperloop
  /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/turbolinks-source-5.0.3/lib/assets/javascripts
  /home/zw963/Project/opal/test_rails_5.1_project/app/views
  /home/zw963/Project/opal/test_rails_5.1_project/node_modules
  /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/react-rails-1.11.0/lib/assets/react-source/development
  /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/react-rails-1.11.0/lib/assets/javascripts
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/context.rb:88:in `resolve'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:259:in `resolve_with_compat'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/context.rb:142:in `require_asset'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/opal-0.10.5/lib/opal/sprockets/processor.rb:69:in `block in process_requires'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/opal-0.10.5/lib/opal/sprockets/processor.rb:67:in `each'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/opal-0.10.5/lib/opal/sprockets/processor.rb:67:in `process_requires'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/opal-0.10.5/lib/opal/sprockets/processor.rb:48:in `evaluate'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/tilt-2.0.7/lib/tilt/template.rb:109:in `render'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/legacy_tilt_processor.rb:25:in `call'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:23:in `block in call'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/utils.rb:200:in `dfs'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:24:in `call'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/environment.rb:30:in `find_asset'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/base.rb:92:in `[]'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/hyperloop-config-0.9.10/lib/hyperloop/imports.rb:105:in `compile_and_compress'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/hyperloop-config-0.9.10/lib/hyperloop-loader-system.js.erb:1:in `_evaluate_template'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/erb_processor.rb:26:in `call'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/erb_processor.rb:13:in `call'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:23:in `block in call'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/utils.rb:200:in `dfs'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:24:in `call'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/sprockets-3.7.1/lib/sprockets/environment.rb:30:in `find_asset'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/hyperloop-config-0.9.10/lib/hyperloop/rail_tie.rb:57:in `block in <class:Railtie>'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/activesupport-5.1.2/lib/active_support/lazy_load_hooks.rb:43:in `execute_hook'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/activesupport-5.1.2/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/activesupport-5.1.2/lib/active_support/lazy_load_hooks.rb:51:in `each'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/activesupport-5.1.2/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/railties-5.1.2/lib/rails/application/finisher.rb:73:in `block in <module:Finisher>'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/railties-5.1.2/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/railties-5.1.2/lib/rails/initializable.rb:30:in `run'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/railties-5.1.2/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /home/zw963/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /home/zw963/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/zw963/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/zw963/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/zw963/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /home/zw963/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /home/zw963/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/zw963/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /home/zw963/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/railties-5.1.2/lib/rails/initializable.rb:58:in `run_initializers'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/railties-5.1.2/lib/rails/application.rb:353:in `initialize!'
	from /home/zw963/Project/opal/test_rails_5.1_project/config/environment.rb:5:in `<top (required)>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:24:in `app'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:80:in `log_to_stdout'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:42:in `start'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:131:in `block in perform'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:126:in `tap'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:126:in `perform'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/railties-5.1.2/lib/rails/command/base.rb:63:in `perform'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/railties-5.1.2/lib/rails/command.rb:44:in `invoke'
	from /home/zw963/.rvm/gems/ruby-2.3.3@test_rails_5.1_project/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

the key is:

`hyper-react` dependency `opal-rails`, but this is not describe in gemspec.

**Comment by catmando** [comment]
we should try to reproduce as we build 0.15 and close if other changes have fixed.
