### ISSUE TITLE
Change ./ext/string requires to react/ext/string

### ISSUE THREAD

**Issue by sollycatprint** [ruby-hyperloop/hyper-react#55]
_From @makevoid on August 7, 2015 13:17_

I've found that there is a require error trying to bundle the code if the the ext/string path is not absolute (gem dir / path)

I think it works well when you are requiring the gem via `path: "./.."` like you do in the examples (in fact they work) but it breaks otherwise

fiy I'm on 2.1.6

Here's how to reproduce:

Gemfile

``` rb
source "http://rubygems.org"

gem "react.rb", github: "zetachang/react.rb"
```

build.rb

``` rb
require 'bundler'
Bundler.require

Opal::Builder.build('react')
```

run: 

```
bundle && ruby build.rb
```

this pr should fix it

there is also some whitespace removal, If you want I can take it out from this PR and have just the two require lines as modified

also, very cool library! I will start to play with it soon! thanks! 

_Copied from original issue: zetachang/react.rb/pull/55_

**Comment by sollycatprint** [comment]
_From @elia on August 7, 2015 13:42_

@makevoid can you paste the error you're getting after `bundle && ruby build.rb`?

**Comment by sollycatprint** [comment]
_From @makevoid on August 7, 2015 13:43_

sure!

```
makevoid@mknix:~/apps/react-rb-builder$ ruby build.rb 
/usr/local/lib/ruby/gems/2.1.0/gems/opal-0.6.3/lib/opal/builder.rb:63:in `find_asset': Could not find asset: ./ext/string (RuntimeError)
    from /usr/local/lib/ruby/gems/2.1.0/gems/opal-0.6.3/lib/opal/builder.rb:39:in `require_asset'
    from /usr/local/lib/ruby/gems/2.1.0/gems/opal-0.6.3/lib/opal/builder.rb:83:in `block in compile_ruby'
    from /usr/local/lib/ruby/gems/2.1.0/gems/opal-0.6.3/lib/opal/builder.rb:82:in `each'
    from /usr/local/lib/ruby/gems/2.1.0/gems/opal-0.6.3/lib/opal/builder.rb:82:in `compile_ruby'
```

here's the full repo https://github.com/makevoid/react-rb-builder
you can switch from the fixed to the original version by changing the file

**Comment by sollycatprint** [comment]
_From @ahti on September 22, 2015 3:48_

I had errors due to the same require. Manually requiring 'react/ext/string' fixed them for now, but imho this pr should be merged.
