### ISSUE TITLE
reactive-ruby branch: uninitialized constant React::Rails::ComponentMount (NameError)

### ISSUE THREAD

**Issue by sollycatprint** [ruby-hyperloop/hyper-react#72]
_From @MichaelSp on October 19, 2015 12:31_

```
Error:[rake --tasks] /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/reactive-ruby-0.7.26/lib/reactive-ruby/rails/component_mount.rb:3:in `<module:Rails>': uninitialized constant React::Rails::ComponentMount (NameError)
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/reactive-ruby-0.7.26/lib/reactive-ruby/rails/component_mount.rb:2:in `<module:ReactiveRuby>'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/reactive-ruby-0.7.26/lib/reactive-ruby/rails/component_mount.rb:1:in `<top (required)>'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/reactive-ruby-0.7.26/lib/reactive-ruby/rails.rb:4:in `require'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/reactive-ruby-0.7.26/lib/reactive-ruby/rails.rb:4:in `<top (required)>'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/reactive-ruby-0.7.26/lib/reactive-ruby.rb:20:in `require'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/reactive-ruby-0.7.26/lib/reactive-ruby.rb:20:in `<top (required)>'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:76:in `require'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:72:in `each'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:72:in `block in require'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:61:in `each'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:61:in `require'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler.rb:134:in `require'
    from /home/michael/src/privat/SocialProjectsHub/config/application.rb:7:in `<top (required)>'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/application.rb:82:in `require'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/application.rb:82:in `preload'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/application.rb:143:in `serve'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/application.rb:131:in `block in run'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/application.rb:125:in `loop'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/application.rb:125:in `run'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/application/boot.rb:18:in `<top (required)>'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/michael/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from -e:1:in `<main>'
```

_Copied from original issue: zetachang/react.rb#72_

**Comment by sollycatprint** [comment]
_From @ajjahn on October 30, 2015 13:56_

@MichaelSp When are you seeing this error? Starting a rails server? Did you add `gem 'react-rails'` to your gem file? To use the rails component helpers, you need react-rails. It's not an explicit dependency because not everyone is using rails.

**Comment by sollycatprint** [comment]
_From @MichaelSp on November 11, 2015 10:42_

Here is a minimal example: 
- `rails new example`
- Change Gemfile according to [Readme](https://github.com/zetachang/react.rb/tree/reactive-ruby)
- `rails s` and you'll see the backtrace.

Here is the example project: https://github.com/MichaelSp/reactive-ruby-example

**Comment by sollycatprint** [comment]
_From @ajjahn on November 11, 2015 12:32_

@MichaelSp The isomorphic version of react-rails is no longer necessary. You gem file should include:

```
gem 'reactive-ruby', '~> 0.7.28'
gem 'react-rails', '~> 1.3.1'
gem 'opal-rails, '~> 0.8.0'
```

**Comment by sollycatprint** [comment]
_From @MichaelSp on November 11, 2015 12:44_

Thanks that worked!
